import Link from "next/link";import {Footer,PageHero,SectionTitle} from "../components";
const groups=[
{name:"B2G Corporativo",text:"Grandes órgãos, empresas públicas, autarquias e estruturas regionais.",focus:["Governança","Escala","Integração","Conformidade"],challenge:"Coordenar múltiplos atores, regras e sistemas sem perder rastreabilidade.",journey:["Diagnóstico institucional","Arquitetura e conformidade","Implantação por ondas","Operação e impacto"],evidence:["Aderência normativa","SLA e continuidade","Indicadores públicos"]},
{name:"B2G SMB",text:"Municípios e organizações públicas que precisam ampliar capacidade de forma proporcional.",focus:["Acesso","Adoção","Sustentação","Impacto"],challenge:"Ganhar capacidade com orçamento, equipe e infraestrutura limitados.",journey:["Prioridade local","Solução proporcional","Formação e adoção","Sustentação"],evidence:["Tempo de atendimento","Cobertura","Capacidade transferida"]},
{name:"B2B Corporativo",text:"Empresas que buscam modernização, inteligência e novas capacidades digitais.",focus:["Eficiência","Dados","Experiência","Segurança"],challenge:"Modernizar operações críticas preservando segurança e continuidade.",journey:["Tese de valor","Caso de negócio","Piloto governado","Escala integrada"],evidence:["ROI e produtividade","Risco reduzido","Adoção"]},
{name:"B2B SMB",text:"Negócios em crescimento que precisam estruturar tecnologia sem perder velocidade.",focus:["Produtividade","Nuvem","Automação","Escala"],challenge:"Profissionalizar tecnologia sem criar complexidade desproporcional.",journey:["Gargalo prioritário","MVP enxuto","Rotina mensurável","Escala sustentável"],evidence:["Tempo poupado","Custo por operação","Conversão"]},
{name:"B2C Digital",text:"Jornadas, produtos e experiências digitais voltadas diretamente às pessoas.",focus:["Experiência","Acesso","Aprendizado","Comunidade"],challenge:"Criar confiança e resolução em jornadas digitais inclusivas.",journey:["Necessidade humana","Protótipo acessível","Teste de uso","Evolução contínua"],evidence:["Resolução","Esforço percebido","Retenção"]},
{name:"B2C Associativo",text:"Redes e organizações conectadas por propósito e valor compartilhado.",focus:["Pertencimento","Cultura","Rede","Desenvolvimento"],challenge:"Converter pertencimento em participação, desenvolvimento e valor compartilhado.",journey:["Propósito comum","Mobilização","Experiência coletiva","Legado da rede"],evidence:["Participação","Conexões ativadas","Desenvolvimento"]},
];
export default function Page(){return <main id="conteudo"><PageHero kicker="Mercados e jornadas" title="Uma arquitetura. Diferentes realidades." lead="A atuação segmentada permite adaptar linguagem, composição, escala, governança e entrega sem perder a identidade do ecossistema."/><section className="content-section"><SectionTitle kicker="Seis segmentos" title="Cada público começa por uma pergunta diferente" lead="Abra cada segmento para percorrer desafio, jornada e evidências de sucesso em dois níveis de profundidade."/><div className="segment-grid depth-grid">{groups.map((g,i)=><article key={g.name}><span>0{i+1}</span><h3>{g.name}</h3><p>{g.text}</p><div>{g.focus.map(x=><b key={x}>{x}</b>)}</div><details><summary>Aprofundar este segmento</summary><h4>Desafio central</h4><p>{g.challenge}</p><h4>Jornada recomendada</h4><ol>{g.journey.map(x=><li key={x}>{x}</li>)}</ol><h4>Evidências esperadas</h4><ul>{g.evidence.map(x=><li key={x}>{x}</li>)}</ul><Link href={`/conectar?segmento=${encodeURIComponent(g.name)}`}>Organizar uma demanda →</Link></details></article>)}</div></section><section className="content-section black"><div className="decision-box dark-box"><small>Princípio comercial</small><h2>Não existe transformação genérica.</h2><p>Escopo, risco, prazo, adoção e governança mudam conforme o ambiente. A IMTS organiza essas diferenças antes de propor o caminho.</p></div></section><Footer/></main>}
