import type {IntegrationKey,IntegrationStatus,LeadIntent} from "./types";

export const functionalMailboxes:Record<LeadIntent,string>={solution:"negocios@imts.com.br",partnership:"partnerships@imts.com.br",initiative:"ive@imts.com.br",talent:"talentos@imts.com.br",capital:"capital@imts.com.br",relations:"relacionamento@imts.com.br"};
export const intentLabels:Record<LeadIntent,string>={solution:"Contratar uma solução",partnership:"Construir uma partnership",initiative:"Submeter uma iniciativa",talent:"Trabalhar na IMTS",capital:"Conhecer a tese de capital",relations:"Imprensa, pesquisa ou impacto"};
export const serviceLevels:Record<LeadIntent,{acknowledgementHours:number;triageHours:number;ownerRole:string}>={
  solution:{acknowledgementHours:1,triageHours:8,ownerRole:"Negócios"},partnership:{acknowledgementHours:1,triageHours:16,ownerRole:"Relações + Negócios"},initiative:{acknowledgementHours:1,triageHours:24,ownerRole:"Inteligência + Estratégias"},talent:{acknowledgementHours:4,triageHours:40,ownerRole:"Gestão de Pessoas"},capital:{acknowledgementHours:1,triageHours:16,ownerRole:"Capital Strategy"},relations:{acknowledgementHours:4,triageHours:24,ownerRole:"Relações"},
};
const requirements:Record<IntegrationKey,string[]>={imts_os:["IMTS_OS_API_URL","IMTS_OS_API_KEY"],lead_webhook:["IMTS_LEAD_WEBHOOK_URL","IMTS_LEAD_WEBHOOK_SECRET"],crm:["IMTS_CRM_API_URL","IMTS_CRM_API_KEY"],email:["IMTS_EMAIL_API_URL","IMTS_EMAIL_API_KEY","IMTS_EMAIL_FROM"],analytics:["IMTS_ANALYTICS_ENDPOINT","IMTS_ANALYTICS_SITE_ID"],consent:["IMTS_CONSENT_VERSION"],storage:["IMTS_STORAGE_MODE"],auth:["IMTS_AUTH_ISSUER","IMTS_AUTH_AUDIENCE"],observability:["IMTS_OTEL_ENDPOINT"]};
export function integrationStatus(env:Record<string,string|undefined>=process.env):IntegrationStatus[]{return (Object.keys(requirements) as IntegrationKey[]).map(key=>{const required=requirements[key];const configured=required.filter(k=>Boolean(env[k]));return{key,state:configured.length===0?"disabled":configured.length===required.length?"configured":"degraded",required,configured}})}
export const publicIntegrationFlags=()=>({assistant:process.env.IMTS_OS_API_URL?"connected":"curated",leadDelivery:process.env.IMTS_LEAD_WEBHOOK_URL?"direct":"email_client",authenticatedWorkspace:process.env.IMTS_AUTH_ISSUER?"available":"planned"} as const);
