import Link from "next/link";
import {Footer,PageHero,SectionTitle} from "../components";
const culture=[
  ["Propósito","Conecta a entrega ao impacto que ela deve gerar.","Decidir pelo sentido comum, não apenas pela conveniência individual."],
  ["Responsabilidade","Assume compromissos, riscos e consequências.","Tornar o andamento visível e pedir ajuda antes de comprometer a entrega."],
  ["Excelência","Eleva o padrão com método e aprendizagem.","Validar qualidade, acessibilidade, segurança e utilidade antes de concluir."],
  ["Colaboração","Compartilha contexto, conhecimento e mérito.","Resolver interfaces entre papéis sem criar dependência invisível."],
  ["Integridade","Age com coerência mesmo quando não há supervisão.","Explicitar conflito, limite, erro ou incerteza com antecedência."],
  ["Evolução","Transforma feedback e evidência em capacidade.","Registrar aprendizados e melhorar o sistema, não apenas a tarefa."],
];
const journey=[
  ["01","Descobrir","Compreender propósito, contexto, papéis e formas de contribuição."],
  ["02","Conectar","Mapear competências, motivação, disponibilidade e aderência cultural."],
  ["03","Contribuir","Assumir uma missão com resultado, responsabilidade e apoio claros."],
  ["04","Desenvolver","Aprender pela prática, mentoria, feedback e repertório compartilhado."],
  ["05","Evoluir","Ampliar autonomia, complexidade e impacto com mérito demonstrável."],
];
export default function Page(){return <main id="conteudo"><PageHero kicker="Gente e cultura" title="Encontre seu papel. Desenvolva sua potência." lead="Pessoas são o centro da transformação. A IMTS conecta propósito, competências, responsabilidade, aprendizagem e mérito para que cada pessoa compreenda como pode contribuir e evoluir."/><section className="content-section"><SectionTitle kicker="Cultura em comportamento" title="Valores só existem quando orientam escolhas" lead="Cada valor precisa ser observável na rotina. Por isso, publicamos significado e exemplo de comportamento esperado."/><div className="target-grid">{culture.map(([name,meaning,example])=><article key={name}><small>Valor</small><h3>{name}</h3><p>{meaning}</p><details><summary>Comportamento esperado</summary><p>{example}</p></details></article>)}</div></section><section className="content-section blue"><SectionTitle light kicker="Jornada de gente" title="Da descoberta à evolução" lead="O encaixe considera conhecimentos, habilidades, capacidades, valores e disponibilidade organizacional. A evolução combina desenvolvimento, avaliação e mérito."/><div className="conversation-flow talent-flow">{journey.map(([n,name,text])=><article key={name}><span>{n}</span><h3>{name}</h3><p>{text}</p></article>)}</div></section><section className="content-section split"><SectionTitle kicker="Liderança e ambiente" title="Alta performance precisa de segurança e clareza" lead="Liderar é criar contexto, acordos, prioridade, feedback e condições para que as pessoas façam o melhor trabalho possível."/><div className="principles"><article><small>Ritos</small><p>Prioridades visíveis, conversas de desenvolvimento, revisões de aprendizagem e reconhecimento de contribuição.</p></article><article><small>Segurança psicológica</small><p>Espaço para dúvidas, discordância respeitosa, reporte de risco e aprendizado com erros.</p></article><article><small>Inclusão</small><p>Acesso proporcional, critérios claros e respeito às diferentes formas de participação e desenvolvimento.</p></article></div></section><section className="content-section"><div className="decision-box"><small>Talentos</small><h2>Comece pela contribuição que você deseja construir.</h2><p>Organize seu perfil, competências, área de interesse e contexto para uma conversa futura, sem promessa de vaga inexistente.</p><Link className="button primary" href="/conectar">Criar briefing de talento ↗</Link></div></section><Footer/></main>}
