"use client";
import {useEffect,useRef,useState} from "react";
export type ConsentChoice={necessary:true;measurement:boolean;preferences:boolean;version:"site-v2"};
const key="imts.consent";
export function readConsent():ConsentChoice|null{try{return JSON.parse(localStorage.getItem(key)||"null")}catch{return null}}
export function track(event:string,properties:Record<string,string|number|boolean>={}){const consent=readConsent();if(event!=="consent_update"&&!consent?.measurement)return;fetch("/api/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event,path:location.pathname,properties}),keepalive:true}).catch(()=>null)}
export default function ConsentManager(){
  const [open,setOpen]=useState(false),[settings,setSettings]=useState(false),[measurement,setMeasurement]=useState(false),[preferences,setPreferences]=useState(false);
  const panel=useRef<HTMLElement>(null),trigger=useRef<HTMLButtonElement>(null);
  useEffect(()=>{queueMicrotask(()=>setOpen(!readConsent()))},[]);
  useEffect(()=>{if(!open)return;const hadChoice=Boolean(readConsent()),previous=document.activeElement as HTMLElement|null;panel.current?.querySelector<HTMLElement>("button,input,a")?.focus();const keydown=(e:KeyboardEvent)=>{if(e.key==="Escape"&&hadChoice){setOpen(false);previous?.focus()}if(e.key==="Tab"){const items=[...panel.current?.querySelectorAll<HTMLElement>("button:not([disabled]),input:not([disabled]),a[href]")||[]];if(!items.length)return;const first=items[0],last=items.at(-1)!;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.documentElement.classList.add("consent-open");document.addEventListener("keydown",keydown);return()=>{document.documentElement.classList.remove("consent-open");document.removeEventListener("keydown",keydown)}},[open]);
  function save(choice:ConsentChoice){localStorage.setItem(key,JSON.stringify({...choice,updatedAt:new Date().toISOString()}));setOpen(false);setSettings(false);trigger.current?.focus();track("consent_update",{measurement:choice.measurement,preferences:choice.preferences})}
  return <><button ref={trigger} className="privacy-trigger" onClick={()=>{setOpen(true);setSettings(true)}}>Privacidade</button>{open&&<section ref={panel} className="consent-panel" role="dialog" aria-modal="true" aria-labelledby="consent-title" aria-describedby="consent-description"><small>CONTROLE DE PRIVACIDADE</small><h2 id="consent-title">Você decide o que compartilhar.</h2><p id="consent-description">Dados necessários mantêm o site funcionando. Medição e preferências só serão ativadas com sua escolha.</p>{settings&&<div className="consent-options"><label><input type="checkbox" checked disabled/><span><b>Necessários</b><small>Sempre ativos para segurança e funcionamento.</small></span></label><label><input type="checkbox" checked={measurement} onChange={e=>setMeasurement(e.target.checked)}/><span><b>Medição</b><small>Ajuda a entender uso e melhorar a experiência.</small></span></label><label><input type="checkbox" checked={preferences} onChange={e=>setPreferences(e.target.checked)}/><span><b>Preferências</b><small>Memoriza escolhas de experiência.</small></span></label></div>}<div><button onClick={()=>save({necessary:true,measurement:false,preferences:false,version:"site-v2"})}>Somente necessários</button>{settings?<button className="primary" onClick={()=>save({necessary:true,measurement,preferences,version:"site-v2"})}>Salvar escolhas</button>:<><button onClick={()=>setSettings(true)}>Configurar</button><button className="primary" onClick={()=>save({necessary:true,measurement:true,preferences:true,version:"site-v2"})}>Aceitar opcionais</button></>}</div><a href="/governanca#privacidade">Entenda nosso compromisso de privacidade →</a></section>}</>
}
