export const solutionDetails={
ia:{code:"IA",title:"Inteligência Artificial e Automação",promise:"Transformar trabalho repetitivo e decisões assistíveis em fluxos governados, mensuráveis e escaláveis.",signals:["Processos manuais e alto retrabalho","Conhecimento disperso","Filas decisórias e baixa rastreabilidade"],deliverables:["Mapa de oportunidades e riscos","Arquitetura de agentes e automações","MVP instrumentado","Governança, avaliação e operação"],questions:["Qual resultado operacional precisa mudar?","Onde estão dados, regras e exceções?","Qual decisão deve continuar humana?"],related:["dados","seguranca","experiencia"]},
dados:{code:"DA",title:"Dados e Inteligência Analítica",promise:"Construir uma base confiável para compreender, decidir, medir e aprender.",signals:["Indicadores conflitantes","Baixa qualidade e rastreabilidade","Decisões sem visão integrada"],deliverables:["Diagnóstico de maturidade","Catálogo e governança","Camada analítica e indicadores","Qualidade, linhagem e rotina decisória"],questions:["Qual decisão os dados precisam sustentar?","Quais fontes são oficiais?","Quem responde por definição e qualidade?"],related:["ia","seguranca","nuvem"]},
seguranca:{code:"CY",title:"Segurança Digital e Confiança Cibernética",promise:"Proteger continuidade, identidades, dados e relações na proporção do risco.",signals:["Acessos excessivos","Ambientes sem visibilidade","Exigências de conformidade e continuidade"],deliverables:["Mapa de riscos e prioridades","Arquitetura de confiança","Controles e resposta a incidentes","Métricas e melhoria contínua"],questions:["Quais ativos não podem parar?","Qual impacto é inaceitável?","Como acessos são concedidos e revogados?"],related:["dados","nuvem","ia"]},
experiencia:{code:"CX",title:"Omnichannel e Experiência Digital",promise:"Integrar canais e jornadas para reduzir esforço, aumentar resolução e fortalecer relações.",signals:["Jornadas fragmentadas","Repetição de informações","Baixa resolução no primeiro contato"],deliverables:["Mapa de jornada e momentos críticos","Arquitetura omnichannel","Protótipo e testes","Métricas de esforço, resolução e confiança"],questions:["Quem vive a jornada?","Onde ocorre maior abandono?","Qual resultado define resolução?"],related:["ia","dados","nuvem"]},
cidades:{code:"IoT",title:"Cidades Inteligentes e IoT",promise:"Transformar sinais do território em consciência operacional e ação coordenada.",signals:["Ativos sem monitoramento","Resposta reativa","Dados territoriais isolados"],deliverables:["Casos de uso priorizados","Arquitetura de sensores e conectividade","Centro de inteligência operacional","Indicadores de serviço e impacto"],questions:["Que evento precisa ser percebido?","Qual decisão será acionada?","Como garantir cobertura e continuidade?"],related:["dados","nuvem","seguranca"]},
nuvem:{code:"CL",title:"Infraestrutura Digital e Nuvem",promise:"Modernizar ambientes com resiliência, elasticidade, segurança e eficiência econômica.",signals:["Legado limitando evolução","Custos sem transparência","Baixa resiliência e automação"],deliverables:["Assessment e plano de modernização","Arquitetura alvo","Migração ou evolução incremental","FinOps, observabilidade e operação"],questions:["O que precisa evoluir sem interromper?","Quais requisitos de disponibilidade?","Como medir custo por valor entregue?"],related:["seguranca","dados","ia"]},
robotica:{code:"RO",title:"Robótica e Aprendizado Tecnológico",promise:"Criar experiências práticas que desenvolvam pensamento computacional, autoria e competências do futuro.",signals:["Aprendizado pouco aplicado","Baixa exposição à tecnologia","Necessidade de inclusão e protagonismo"],deliverables:["Jornada pedagógica","Kits, laboratórios e desafios","Formação de facilitadores","Avaliação de aprendizagem e impacto"],questions:["Qual competência deve ser desenvolvida?","Quem aprende e em qual contexto?","Como garantir acesso, segurança e continuidade?"],related:["ia","dados","experiencia"]},
} as const;
export type SolutionSlug=keyof typeof solutionDetails;
export const personas=[{id:"lider",name:"Liderança executiva",need:"Clareza para priorizar e decidir",path:"Tese → diagnóstico → direção",cta:"Organizar um desafio",intent:"solution"},{id:"publico",name:"Gestão pública",need:"Impacto, conformidade e capacidade de execução",path:"Problema público → arquitetura → entrega",cta:"Estruturar uma agenda",intent:"relations"},{id:"inovacao",name:"Inovação e produto",need:"Evidência para validar e escalar",path:"Hipótese → IVE → escala",cta:"Submeter uma iniciativa",intent:"initiative"},{id:"tecnologia",name:"Tecnologia e operação",need:"Integração, segurança e continuidade",path:"Estado atual → arquitetura → operação",cta:"Mapear capacidade",intent:"solution"},{id:"parceiro",name:"Parceiro do ecossistema",need:"Papel, complementaridade e geração de valor",path:"Contribuição → partnership → composição",cta:"Encontrar meu papel",intent:"partnership"},{id:"talento",name:"Talento e especialista",need:"Pertencimento, contribuição e evolução",path:"Identidade → papel → desenvolvimento",cta:"Conhecer a jornada",intent:"talent"},{id:"capital",name:"Capital e conselho",need:"Tese, governança e risco",path:"Evidência → bifurcação → acompanhamento",cta:"Conhecer a tese",intent:"capital"}] as const;
