export type KnowledgeEntry={id:string;title:string;keywords:string[];answer:string;href:string;source:string;updated:string};
export const knowledgeBase:KnowledgeEntry[]=[
{id:"ecosystem",title:"O que é a IMTS",keywords:["imts","ecossistema","empresa","propósito","faz"],answer:"A IMTS é um ecossistema que conecta pessoas, tecnologia, método e capital para transformar ideias e desafios em soluções aplicáveis, escaláveis e sustentáveis.",href:"/ecossistema",source:"Identidade institucional",updated:"2026-07-19"},
{id:"solutions",title:"Como contratar uma solução",keywords:["contratar","solução","projeto","proposta","negócios"],answer:"O primeiro passo é organizar o contexto, o resultado esperado, as restrições e as evidências disponíveis. O briefing é encaminhado ao papel de Negócios e pode envolver Inteligência e Operação.",href:"/conectar?intent=solution",source:"Jornada de negócios",updated:"2026-07-19"},
{id:"ive",title:"Método IVE",keywords:["ive","ideia","iniciativa","validação","protótipo","escala","funil"],answer:"O IVE conduz iniciativas da origem à escala por estágios com perguntas de gate, responsáveis, evidências e uma bifurcação de capital entre produtização e operação.",href:"/ive",source:"Método IVE",updated:"2026-07-19"},
{id:"partnership",title:"Partnerships",keywords:["parceria","partner","partnership","aliado","território"],answer:"A IMTS organiza partnerships em cinco formas: find, business, service, territory e aliado estratégico. O enquadramento depende da contribuição, responsabilidade e valor compartilhado.",href:"/partnerships",source:"Modelo de partnerships",updated:"2026-07-19"},
{id:"talent",title:"Talentos",keywords:["trabalhar","talento","carreira","vaga","equipe","especialista"],answer:"A participação de talentos é estruturada por papel, competências, responsabilidades e evolução. Pessoas não são expostas no site; o contato segue para o endereço funcional de Gestão de Pessoas.",href:"/talentos",source:"Jornada de talentos",updated:"2026-07-19"},
{id:"privacy",title:"Privacidade e segredo",keywords:["privacidade","segredo","cliente","case","dados","confidencial"],answer:"A IMTS protege o segredo dos negócios. Clientes, estratégias e operações confidenciais não são apresentados publicamente. Confiança é demonstrada por governança, métodos e números macro aprovados.",href:"/governanca#privacidade",source:"Centro de confiança",updated:"2026-07-19"},
{id:"ai",title:"IMTS.OS e IA",keywords:["ia","chat","imts.os","assistente","inteligência artificial"],answer:"O assistente público orienta com conhecimento institucional aprovado e transbordo humano. O nível autenticado será conectado ao IMTS.OS com autorização por papel e fontes protegidas.",href:"/imts-os",source:"Arquitetura IMTS.OS",updated:"2026-07-19"},
{id:"capital",title:"Capital",keywords:["capital","investimento","investidor","venture","bifurcação"],answer:"A tese de capital participa de pontos de decisão governados, especialmente na bifurcação entre produto interno e venture autônomo. Informações sensíveis permanecem em ambiente autorizado.",href:"/capital",source:"Tese de capital",updated:"2026-07-19"},
{id:"impact",title:"Impacto",keywords:["impacto","ods","sustentabilidade","legado"],answer:"A IMTS conecta inovação, prosperidade e responsabilidade, com o compromisso de contribuir para os 17 Objetivos de Desenvolvimento Sustentável até 2030.",href:"/impacto",source:"Compromisso de impacto",updated:"2026-07-19"},
];
const normalize=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
export function answerFromKnowledge(question:string){const terms=normalize(question).split(/[^a-z0-9.]+/).filter(x=>x.length>2);const ranked=knowledgeBase.map(entry=>{const hay=normalize(`${entry.title} ${entry.keywords.join(" ")} ${entry.answer}`);return{entry,score:terms.reduce((n,t)=>n+(hay.includes(t)?1:0),0)}}).sort((a,b)=>b.score-a.score);const best=ranked[0];if(!best||best.score===0)return{answer:"Ainda não encontrei uma resposta segura na base institucional. Posso ajudar você a explorar os temas ou encaminhar a pergunta ao atendimento humano.",sources:[],suggestions:knowledgeBase.slice(0,3).map(x=>({title:x.title,href:x.href})),confidence:"low"};return{answer:best.entry.answer,sources:[{title:best.entry.source,href:best.entry.href,updated:best.entry.updated}],suggestions:ranked.slice(1,4).map(x=>({title:x.entry.title,href:x.entry.href})),confidence:best.score>=2?"high":"medium"}}
