"use client";
import {useEffect,useMemo,useState} from "react";
import {track} from "./ConsentManager";
import Link from "next/link";
const knowledge=[
  {keys:"solução contratar tecnologia projeto",answer:"Para contratar ou compor uma solução, comece por um briefing de contexto. A demanda será direcionada ao papel de Negócios, com apoio de Inteligência e Operação.",href:"/conectar?intent=solucao"},
  {keys:"partner partnership parceria ecossistema",answer:"Há cinco portas de parceria: find, business, service, territory e aliado estratégico. O melhor enquadramento depende da contribuição e do resultado esperado.",href:"/partnerships"},
  {keys:"ive ideia iniciativa validação escala",answer:"O IVE conduz iniciativas da origem à escala, com evidências, responsáveis e pontos de decisão. Você pode explorar todos os estágios antes de submeter uma iniciativa.",href:"/ive"},
  {keys:"trabalhar talento carreira equipe",answer:"A jornada de talentos é organizada por papel, competências e evolução — sem exposição de pessoas. Consulte as formas de participação e envie seu contexto.",href:"/talentos"},
  {keys:"privacidade segurança dados confiança",answer:"A IMTS adota minimização de dados, acesso proporcional ao papel e responsabilidade humana. Estratégias, clientes e operações confidenciais não são expostos.",href:"/governanca"},
];
export default function SiteExperience(){
  const [open,setOpen]=useState(false),[chat,setChat]=useState(false),[contrast,setContrast]=useState(false),[large,setLarge]=useState(false),[q,setQ]=useState(""),[remote,setRemote]=useState(""),[asking,setAsking]=useState(false);
  useEffect(()=>{document.documentElement.classList.toggle("high-contrast",contrast);document.documentElement.classList.toggle("large-text",large)},[contrast,large]);
  useEffect(()=>{track("page_view");const click=(event:MouseEvent)=>{const link=(event.target as Element)?.closest?.("[data-track]") as HTMLElement|null;if(link?.dataset.track)track("cta_click",{action:link.dataset.track})};document.addEventListener("click",click);return()=>document.removeEventListener("click",click)},[]);
  const result=useMemo(()=>{const words=q.toLowerCase().split(/\s+/).filter(Boolean);return knowledge.map(x=>({...x,score:words.filter(w=>x.keys.includes(w)).length})).sort((a,b)=>b.score-a.score)[0]},[q]);
  async function ask(){if(q.trim().length<3)return;track("assistant_query");setAsking(true);setRemote("");try{const response=await fetch("/api/ai/query",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({question:q,level:"public",context:{path:location.pathname}})});if(response.ok){const data=await response.json();setRemote(data.answer||data.response||"")}}catch{setRemote("O serviço está temporariamente indisponível. Consulte a base institucional ou fale com o atendimento humano.")}finally{setAsking(false)}}
  return <><a className="skip-link" href="#conteudo">Ir para o conteúdo</a><div className="access-tools" aria-label="Preferências de acessibilidade"><button onClick={()=>setLarge(!large)} aria-pressed={large}>A+</button><button onClick={()=>setContrast(!contrast)} aria-pressed={contrast}>Contraste</button></div><button className="menu-toggle" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="mobile-navigation">{open?"Fechar":"Menu"}</button>{open&&<nav id="mobile-navigation" className="mobile-navigation" aria-label="Navegação móvel"><a href="/ecossistema">Ecossistema</a><Link href="/solucoes">Soluções</Link><a href="/segmentos">Segmentos</a><a href="/ive">Método IVE</a><a href="/partnerships">Partnerships</a><a href="/insights">Insights</a><a href="/imts-os">IMTS.OS</a><a href="/conectar">Conectar</a></nav>}<button className="ai-launcher" onClick={()=>setChat(!chat)} aria-expanded={chat} aria-controls="imts-os-assistant"><span>IMTS.OS</span><b>{chat?"×":"IA"}</b></button>{chat&&<aside id="imts-os-assistant" className="ai-panel" aria-label="Assistente público IMTS.OS"><small>IMTS.OS · NÍVEL PÚBLICO</small><h2>Como posso orientar?</h2><p>Consulte métodos, capacidades e portas de entrada. Não inclua informações confidenciais.</p><label htmlFor="ai-question">Sua pergunta</label><textarea id="ai-question" value={q} onChange={e=>{setQ(e.target.value);setRemote("")}} placeholder="Ex.: Como submeter uma iniciativa?" rows={3}/><button className="ai-ask" onClick={ask} disabled={asking}>{asking?"Consultando…":"Perguntar"}</button>{q&&<div className="ai-answer" aria-live="polite"><p>{remote||(result?.score?result.answer:"Ainda não encontrei uma resposta precisa. Posso encaminhar sua dúvida ao papel responsável.")}</p><a href={remote?"/imts-os":result?.score?result.href:"mailto:imtsos@imts.com.br?subject=Dúvida encaminhada pelo IMTS.OS"}>{remote?"Sobre o IMTS.OS →":result?.score?"Aprofundar →":"Encaminhar para atendimento →"}</a></div>}<a className="ai-human" href="mailto:imtsos@imts.com.br?subject=Atendimento humano via IMTS.OS">Falar com atendimento humano</a><em>Respostas orientativas. Decisões relevantes permanecem humanas.</em></aside>}</>;
}
