"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {track} from "./ConsentManager";
import Link from "next/link";
const knowledge=[
  {keys:"solução contratar tecnologia projeto",answer:"Para contratar ou compor uma solução, comece por um briefing de contexto. A demanda será direcionada ao papel de Negócios, com apoio de Inteligência e Operação.",href:"/conectar?intent=solucao"},
  {keys:"partner partnership parceria ecossistema",answer:"Há cinco portas de parceria: find, business, service, territory e aliado estratégico. O melhor enquadramento depende da contribuição e do resultado esperado.",href:"/partnerships"},
  {keys:"ive ideia iniciativa validação escala",answer:"O IVE conduz iniciativas da origem à escala, com evidências, responsáveis e pontos de decisão. Você pode explorar todos os estágios antes de submeter uma iniciativa.",href:"/ive"},
  {keys:"trabalhar talento carreira equipe",answer:"A jornada de talentos é organizada por papel, competências e evolução — sem exposição de pessoas. Consulte as formas de participação e envie seu contexto.",href:"/talentos"},
  {keys:"privacidade segurança dados confiança",answer:"A IMTS adota minimização de dados, acesso proporcional ao papel e responsabilidade humana. Estratégias, clientes e operações confidenciais não são expostos.",href:"/governanca"},
];
export default function SiteExperience(){
  const [open,setOpen]=useState(false),[chat,setChat]=useState(false),[contrast,setContrast]=useState(false),[large,setLarge]=useState(false),[q,setQ]=useState(""),[remote,setRemote]=useState(""),[asking,setAsking]=useState(false);
  const menuButton=useRef<HTMLButtonElement>(null),chatButton=useRef<HTMLButtonElement>(null),panel=useRef<HTMLElement>(null);
  useEffect(()=>{document.documentElement.classList.toggle("high-contrast",contrast);document.documentElement.classList.toggle("large-text",large)},[contrast,large]);
  useEffect(()=>{document.documentElement.classList.toggle("overlay-open",open||chat);return()=>document.documentElement.classList.remove("overlay-open")},[open,chat]);
  useEffect(()=>{if(!open&&!chat)return;const previous=document.activeElement as HTMLElement|null;const target=panel.current?.querySelector<HTMLElement>("a,button,textarea");target?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){setOpen(false);setChat(false);previous?.focus()}if(event.key==="Tab"){const items=[...panel.current?.querySelectorAll<HTMLElement>("a[href],button:not([disabled]),textarea")||[]];if(!items.length)return;const first=items[0],last=items.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[open,chat]);
  useEffect(()=>{track("page_view");const click=(event:MouseEvent)=>{const link=(event.target as Element)?.closest?.("[data-track]") as HTMLElement|null;if(link?.dataset.track)track("cta_click",{action:link.dataset.track})};document.addEventListener("click",click);return()=>document.removeEventListener("click",click)},[]);
  const result=useMemo(()=>{const words=q.toLowerCase().split(/\s+/).filter(Boolean);return knowledge.map(x=>({...x,score:words.filter(w=>x.keys.includes(w)).length})).sort((a,b)=>b.score-a.score)[0]},[q]);
  async function ask(){if(q.trim().length<3)return;track("assistant_query");setAsking(true);setRemote("");try{const response=await fetch("/api/ai/query",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({question:q,level:"public",context:{path:location.pathname}})});if(response.ok){const data=await response.json();setRemote(data.answer||data.response||"")}}catch{setRemote("O serviço está temporariamente indisponível. Consulte a base institucional ou fale com o atendimento humano.")}finally{setAsking(false)}}
  return <><a className="skip-link" href="#conteudo">Ir para o conteúdo</a><div className="access-tools" aria-label="Preferências de acessibilidade"><button onClick={()=>setLarge(!large)} aria-pressed={large}>A+</button><button onClick={()=>setContrast(!contrast)} aria-pressed={contrast}>Contraste</button></div><button ref={menuButton} className="menu-toggle" onClick={()=>{setOpen(!open);setChat(false)}} aria-expanded={open} aria-controls="mobile-navigation">{open?"Fechar":"Menu"}</button>{open&&<nav ref={panel as React.RefObject<HTMLElement>} id="mobile-navigation" className="mobile-navigation" aria-label="Navegação móvel"><a href="/ecossistema">Ecossistema</a><Link href="/segmentos">Segmentos</Link><Link href="/solucoes">Soluções</Link><a href="/direcao">Direção</a><a href="/impacto">Impacto e legado</a><a href="/talentos">Gente e cultura</a><a href="/iara">IARA</a><a href="/ive">Método IVE</a><a href="/conectar">Conectar</a></nav>}<button ref={chatButton} className="ai-launcher" onClick={()=>{const next=!chat;setChat(next);setOpen(false);if(next)track("assistant_open")}} aria-expanded={chat} aria-controls="imts-os-assistant"><span>IARA</span><b>{chat?"×":"IA"}</b></button>{chat&&<aside ref={panel} id="imts-os-assistant" className="ai-panel" role="dialog" aria-modal="true" aria-label="IARA, inteligência artificial da IMTS"><small>IARA · INTELIGÊNCIA DA IMTS</small><h2>O que vamos colocar em movimento?</h2><p>Compreendo desafios, conecto possibilidades e transformo intenção em caminhos de ação. Não inclua informações confidenciais.</p><label htmlFor="ai-question">Seu desafio ou pergunta</label><textarea id="ai-question" value={q} onChange={e=>{setQ(e.target.value);setRemote("")}} placeholder="Ex.: Como transformar esta ideia em uma iniciativa?" rows={3}/><button className="ai-ask" onClick={ask} disabled={asking}>{asking?"Consultando…":"Conversar com a IARA"}</button>{q&&<div className="ai-answer" aria-live="polite"><p>{remote||(result?.score?result.answer:"Ainda não encontrei evidência suficiente para uma resposta precisa. Posso encaminhar sua dúvida ao papel responsável.")}</p><a href={remote?"/iara":result?.score?result.href:"mailto:imtsos@imts.com.br?subject=Dúvida encaminhada pela IARA"}>{remote?"Conhecer a IARA →":result?.score?"Aprofundar →":"Encaminhar para atendimento →"}</a></div>}<a className="ai-human" href="mailto:imtsos@imts.com.br?subject=Atendimento humano via IARA">Falar com uma pessoa</a><em>IARA orienta. Decisões relevantes permanecem humanas.</em></aside>}</>;
}
