import Link from "next/link";
import {Footer,PageHero,SectionTitle} from "../components";
const agendas=[
  {ods:"ODS 4 · 8 · 9",title:"Capacidades e prosperidade",commitment:"Ampliar aprendizagem, trabalho produtivo e inovação aplicável.",indicators:["pessoas e organizações capacitadas","soluções adotadas e sustentadas","capacidade transferida ao território"]},
  {ods:"ODS 10 · 11 · 16",title:"Territórios e instituições",commitment:"Fortalecer acesso, serviços, confiança e capacidade institucional.",indicators:["acesso e experiência do cidadão","tempo ou qualidade do serviço","governança e transparência"]},
  {ods:"ODS 5 · 12 · 13 · 17",title:"Responsabilidade compartilhada",commitment:"Integrar inclusão, uso responsável de recursos e alianças de impacto.",indicators:["participação e inclusão","eficiência de recursos","parcerias com resultado comprovado"]},
];
const legacy=[
  ["Humano","Conhecimento, autonomia, liderança e oportunidades que permanecem nas pessoas."],
  ["Institucional","Métodos, governança e capacidade de execução incorporados às organizações."],
  ["Territorial","Infraestrutura, redes e serviços que ampliam prosperidade e qualidade de vida."],
  ["Intergeracional","Decisões presentes que preservam possibilidades e reduzem riscos futuros."],
];
export default function Page(){return <main id="conteudo"><PageHero kicker="Impacto e legado" title="Crescer importa. O que o crescimento transforma importa mais." lead="A agenda 2030 conecta os 17 ODS a compromissos, iniciativas, indicadores, responsáveis e evidências. O legado amplia o horizonte para aquilo que deve permanecer depois de cada projeto."/><section className="content-section"><SectionTitle kicker="Matriz de impacto" title="Do compromisso à evidência" lead="Agrupamos os ODS em agendas operáveis. Cada agenda explicita o resultado buscado e as famílias de indicadores que deverão receber baseline, meta, prazo e fonte."/><div className="target-grid">{agendas.map(a=><article key={a.title}><small>{a.ods}</small><h3>{a.title}</h3><p>{a.commitment}</p><details><summary>Indicadores acompanhados</summary><ul>{a.indicators.map(i=><li key={i}>{i}</li>)}</ul></details></article>)}</div></section><section className="content-section black"><SectionTitle light kicker="Cadeia de comprovação" title="Impacto não é intenção publicada como resultado." lead="Só tratamos um resultado como evidência quando há definição, baseline, período, fonte, responsável e possibilidade de verificação."/><div className="impact-method"><div><b>01</b><span>Alvo</span></div><i>→</i><div><b>02</b><span>Iniciativa</span></div><i>→</i><div><b>03</b><span>Indicador</span></div><i>→</i><div><b>04</b><span>Evidência</span></div></div></section><section className="content-section" id="legado"><SectionTitle kicker="Legado" title="O que deve permanecer quando a entrega termina" lead="Legado é capacidade duradoura, não memória promocional. Avaliamos quatro dimensões e três horizontes: continuidade, transformação e contribuição intergeracional."/><div className="pillar-grid legacy-light">{legacy.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="content-section"><div className="decision-box"><small>Conexão de impacto</small><h2>Uma causa ou território pode se conectar às capacidades do ecossistema.</h2><p>O primeiro passo é definir o problema, as pessoas afetadas, a mudança esperada e a evidência mínima de progresso.</p><Link className="button primary" href="/conectar">Apresentar uma agenda de impacto ↗</Link></div></section><Footer/></main>}
