"use client";
import {useEffect,useMemo,useState} from "react";
import {track} from "../ConsentManager";
import {personas} from "../content";
const routes={"Contratar uma solução":"negocios@imts.com.br","Construir uma partnership":"partnerships@imts.com.br","Submeter uma iniciativa":"ive@imts.com.br","Trabalhar na IMTS":"talentos@imts.com.br","Conhecer a tese de capital":"capital@imts.com.br","Imprensa, pesquisa ou impacto":"relacionamento@imts.com.br"} as const;
const intents=Object.keys(routes) as Array<keyof typeof routes>;
export default function BriefingForm(){
  const [intent,setIntent]=useState<keyof typeof routes>(intents[0]);const [name,setName]=useState("");const [email,setEmail]=useState("");const [org,setOrg]=useState("");const [role,setRole]=useState("");const [challenge,setChallenge]=useState("");const [consent,setConsent]=useState(false);const [copied,setCopied]=useState(false);const [status,setStatus]=useState<"idle"|"sending"|"sent"|"fallback">("idle");const [reference,setReference]=useState("");
  useEffect(()=>{queueMicrotask(()=>{const p=new URLSearchParams(location.search),topic=p.get("topic"),personaId=p.get("persona"),segment=p.get("segmento"),requested=p.get("intent")||p.get("circulo");const aliases:Record<string,keyof typeof routes>={solution:"Contratar uma solução",solucao:"Contratar uma solução",iara:"Contratar uma solução",partnership:"Construir uma partnership",parceria:"Construir uma partnership",initiative:"Submeter uma iniciativa",ive:"Submeter uma iniciativa",talent:"Trabalhar na IMTS",talentos:"Trabalhar na IMTS",capital:"Conhecer a tese de capital",relations:"Imprensa, pesquisa ou impacto",impacto:"Imprensa, pesquisa ou impacto",imprensa:"Imprensa, pesquisa ou impacto"};const persona=personas.find(x=>x.id===personaId);if(persona){setRole(persona.name);setIntent(aliases[persona.intent]);setChallenge(`${persona.need}\n\nContexto que desejo aprofundar:\n`)}else if(requested&&aliases[requested.toLowerCase()])setIntent(aliases[requested.toLowerCase()]);if(topic)setChallenge(`Quero compreender como a capacidade ${topic.toUpperCase()} pode contribuir para este contexto:\n\n`);if(segment)setChallenge(`Quero compreender oportunidades para o segmento ${segment.replaceAll("-"," ")}.\n\nContexto:\n`);})},[]);
  const summary=useMemo(()=>`BRIEFING INICIAL · ECOSSISTEMA IMTS\n\nIntenção: ${intent}\nNome: ${name||"[preencher]"}\nE-mail: ${email||"[preencher]"}\nOrganização: ${org||"[preencher]"}\nPapel/função: ${role||"[preencher]"}\nDesafio ou oportunidade:\n${challenge||"[descrever]"}\n\nGerado no site institucional IMTS.`,[intent,name,email,org,role,challenge]);
  async function copy(){await navigator.clipboard.writeText(summary);setCopied(true);setTimeout(()=>setCopied(false),1800)}
  function download(){const blob=new Blob([summary],{type:"text/plain;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="briefing-imts.txt";a.click();URL.revokeObjectURL(a.href)}
  const intentCodes:Record<keyof typeof routes,string>={"Contratar uma solução":"solution","Construir uma partnership":"partnership","Submeter uma iniciativa":"initiative","Trabalhar na IMTS":"talent","Conhecer a tese de capital":"capital","Imprensa, pesquisa ou impacto":"relations"};
  function mailFallback(){setStatus("fallback");location.href=`mailto:${routes[intent]}?subject=${encodeURIComponent(`[Site IMTS] ${intent} · ${org||name}`)}&body=${encodeURIComponent(summary)}`}
  async function send(){if(!name||!email||!challenge||!consent)return;track("form_submit",{intent:intentCodes[intent]});setStatus("sending");try{const response=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({intent:intentCodes[intent],name,email,organization:org,role,message:challenge,consent})});const data=await response.json();setReference(data.reference||"");if(response.ok&&data.code!=="accepted_pending_delivery"){setStatus("sent");return}if(response.ok&&data.code==="accepted_pending_delivery"){mailFallback();return}}catch{}mailFallback()}
  return <div className="briefing-grid"><form className="briefing-form" onFocus={()=>status==="idle"&&track("form_start",{intent:intentCodes[intent]})} onSubmit={e=>{e.preventDefault();send()}}><label>Como você quer se conectar?<select value={intent} onChange={e=>setIntent(e.target.value as keyof typeof routes)}>{intents.map(x=><option key={x}>{x}</option>)}</select></label><p className="route-note">Encaminhamento: <strong>{routes[intent]}</strong></p><div className="field-row"><label>Seu nome *<input required autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Nome completo"/></label><label>Seu e-mail *<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@empresa.com.br"/></label></div><div className="field-row"><label>Organização<input autoComplete="organization" value={org} onChange={e=>setOrg(e.target.value)} placeholder="Empresa ou instituição"/></label><label>Seu papel/função<input autoComplete="organization-title" value={role} onChange={e=>setRole(e.target.value)} placeholder="Ex.: líder de inovação"/></label></div><label>Qual desafio, oportunidade ou iniciativa devemos compreender? *<textarea required value={challenge} onChange={e=>setChallenge(e.target.value)} rows={7} placeholder="Contexto, objetivo, prazo e resultado esperado"/></label><label className="check"><input required type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Autorizo o uso destas informações para responder à solicitação, conforme a finalidade informada.</span></label><button disabled={status==="sending"||status==="sent"} className="button primary" type="submit">{status==="sending"?"Encaminhando…":status==="sent"?"Solicitação recebida ✓":"Enviar solicitação ↗"}</button><p className="form-status" aria-live="polite">{status==="sent"?`Recebemos sua solicitação. Protocolo: ${reference}`:status==="fallback"?`A solicitação foi preservada${reference?` no protocolo ${reference}`:""}, mas a entrega ao responsável está pendente. Abrimos seu e-mail como contingência.`:"O módulo tentará o canal integrado e usará seu aplicativo de e-mail como contingência."}</p></form><aside className="briefing-output"><small>Briefing estruturado</small><pre>{summary}</pre><div><button type="button" onClick={copy}>{copied?"Copiado":"Copiar briefing"}</button><button type="button" className="secondary" onClick={download}>Baixar .txt</button></div><p>Não inclua segredos de negócio, credenciais ou dados pessoais desnecessários.</p></aside></div>;
}
