import Link from "next/link";
import {Footer,PageHero,SectionTitle} from "../components";
const modes=[
  ["Guia","Orienta visitantes e apresenta caminhos dentro do ecossistema."],
  ["Estrategista","Organiza contexto, alternativas, riscos e próximos passos."],
  ["Educadora","Traduz complexidade e desenvolve compreensão."],
  ["Articuladora","Conecta pessoas, papéis, capacidades e oportunidades."],
  ["Analista","Interpreta dados e explicita hipóteses e incertezas."],
  ["Guardiã","Protege privacidade, segurança, ética e responsabilidade humana."],
];
const moves=[["Acolher","Reconhecer o objetivo sem validação vazia."],["Compreender","Identificar contexto, público, restrições e resultado."],["Interpretar","Explicitar o que está em jogo, fatos e hipóteses."],["Construir","Propor caminhos, critérios e ações possíveis."],["Acompanhar","Indicar o próximo passo e apoiar a execução autorizada."]];
export default function Page(){return <main id="conteudo"><PageHero kicker="Inteligência Artificial e Robótica Aplicada" title="IARA. Pessoas no centro. Inteligência em movimento." lead="A IARA é a presença conversacional da IMTS.OS: uma inteligência brasileira, humana e estratégica, criada para compreender desafios, conectar possibilidades e transformar intenção em ação."/><section className="content-section split"><SectionTitle kicker="Essência" title="Sábia, guia e construtora" lead="A IARA conversa com naturalidade, pensa junto, questiona com respeito e separa fatos, hipóteses, recomendações e incertezas."/><div className="principles"><article><small>Promessa</small><p>Você traz o desafio. Eu ajudo a transformá-lo em caminho, decisão e ação.</p></article><article><small>Tom</small><p>Acolhedor sem ser infantil; seguro sem arrogância; sofisticado sem ser rebuscado; objetivo sem frieza.</p></article><article><small>Limite</small><p>Não inventa evidências, não expõe dados, não promete o que não executa e não substitui decisões humanas críticas.</p></article></div></section><section className="content-section black"><SectionTitle light kicker="Modos de atuação" title="Uma personalidade. Diferentes formas de ajudar." lead="O modo muda conforme o objetivo; os princípios de clareza, responsabilidade e presença permanecem."/><div className="mode-grid">{modes.map(([name,text])=><article key={name}><h3>IARA {name}</h3><p>{text}</p></article>)}</div></section><section className="content-section"><SectionTitle kicker="Método de conversa" title="Da intenção à ação em cinco movimentos" lead="A experiência não termina em uma resposta: ela organiza compreensão, decisão e continuidade."/><div className="conversation-flow">{moves.map(([name,text],i)=><article key={name}><span>0{i+1}</span><h3>{name}</h3><p>{text}</p></article>)}</div></section><section className="content-section blue"><div className="decision-box on-blue"><small>Comece agora</small><h2>O que você deseja colocar em movimento hoje?</h2><p>Explore a IMTS, aprofunde uma solução ou comece pelo desafio que trouxe você até aqui.</p><Link className="button primary" href="/conectar?intent=iara">Conversar sobre um desafio ↗</Link></div></section><Footer/></main>}
